version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../var/log/nginx:/var/log/nginx
      - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
      - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites-enabled/:/etc/nginx/conf.d/
      - ./config/nginx/includes:/etc/nginx/includes
      - ./:/app:cached
    networks:
      - mynetwork
    volumes_from:
      - php82

  php82:
    build: docker-images/php82
    container_name: php82
    volumes:
      - ..:/var/www/html
    networks:
      - mynetwork
  #   links:
  #     - mysql

  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ../databases/mysql57:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_USER: root
  #     MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_HOST=192.168.1.12
      - PMA_USER=mdsw
      - PMA_PASSWORD=mdsw1011
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
